version: "3.3"
services:
  web_server:
    build: .
    ports:
      - 5000:5000
   links:
     - cassandra:cassandradb-01
  cassandra:
    image: cassandra:latest
    container_name: cassandra
    command: /docker-entrypoint.sh cassandra -f
    ports:
      - 9042:9042
      - 9160:9160

