version: '2.1'
services:
  discovery-host:
    image: new-discovery-server
    ports:
      - "8761:8761"
  gateway-host:
    image: new-api-gateway
    ports:
      - "5000:5000"
    links:
      - discovery-host:discovery-host
    depends_on:
      - discovery-host
  postgres-host:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: postgres
  meta-host:
    image: new-meta-server
    ports:
      - "5001:5001"
    links:
      - postgres-host:postgres-host
      - discovery-host:discovery-host
    depends_on:
      - postgres-host
      - discovery-host
  zookeeper-host:
    image: zookeeper:3.4.9
    ports:
      - "2181:2181"
  kafka-host:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    links:
      - zookeeper-host:zookeeper-host
    depends_on:
      - zookeeper-host
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-host:2181
      KAFKA_ADVERTISED_HOST_NAME: kafka-host
      KAFKA_CREATE_TOPICS: "kafka-io:1:1"
  cassandra-host:
    image: cassandra
    ports:
      - "9160:9160"
      - "9042:9042"
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "9042"]
      interval: 30s
      timeout: 10s
      retries: 5
  io-host:
    image: new-io-server
    ports:
      - "5002:5002"
    links:
      - discovery-host:discovery-host
      - cassandra-host:cassandra-host
      - kafka-host:kafka-host
    depends_on:
      - discovery-host
      - cassandra-host
      - kafka-host
    restart: on-failure


