server:
  port: 5000

kafka:
  bootstrap-servers: localhost:9092
  topic:
    kafka-io: kafka-io

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true

ribbon:
  eureka:
    enabled: true

