server:
  port: 5000

kafka:
  bootstrap-servers: localhost:9092
  topic:
    kafka-io: kafka-io

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
